# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Dist & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        
    - name: Setup Git
      run: |
        git config user.name "Github Actions"
        git config user.email "<>"
        
    - name: Use Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dev Packages
      run: npm ci

    - name: Build Dist
      run: npm run build --if-present

    - name: Test and Coverage 
      run: npm run test:coverage --if-present

    - name: Update Badges
      run: npm run update:badges --if-present
            
    - name: Bump Version
      run: npm version patch
      
    - name: Push Version and Badges To Repo
      run: |
        git push --follow-tags origin main
